#ifndef ENUMS_H
#define ENUMS_H

enum class Comenzi {
  COMANDA_CREARE_LISTA,
  COMANDA_ADAUGA_NOD,
  COMANDA_STERGE_NOD,
  COMANDA_STERGE_LISTA,
  COMANDA_LUNGIME_LISTA,
  COMANDA_INVERSARE_LISTA,
  COMANDA_VERIFICARE_OPERATOR_INDICE,
  COMANDA_VERIFICA_LISTA_GOALA,
  COMANDA_VERIFICA_2_LISTE_EGALE,
  COMANDA_VERIFICA_2_LISTE_NON_EGALE,
  COMANDA_VERIFICA_OP_MAI_MIC,
  COMANDA_VERIFICA_OP_MAI_MIC_EGAL,
  COMANDA_VERIFICA_OP_MAI_MARE,
  COMANDA_VERIFICA_OP_MAI_MARE_EGAL,
  COMANDA_CONCATENARE,
  COMANDA_AFISARE_LISTA,
  COMANDA_AFISARE_LISTA_FOLOSIND_ITERATOR,
  COMANDA_ADUNARE_LDI,
  COMANDA_STOP_PROGRAM,

  MAX_COMENZI
};

#endif
